CAFE_VIP/Areas/Admin/Controllers/CatelogyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CAFE_VIP.Areas.Admin.Controllers
{
    public class CatelogyController : Controller
    {
        // GET: Admin/Catelogy
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
    }
}

CAFE_VIP/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CAFE_VIP.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        // GET: Admin/Order
        public ActionResult Index()
        {
            return View();
        }
    }
}

CAFE_VIP/Areas/Admin/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.EF;

namespace CAFE_VIP.Areas.Admin.Controllers
{
    public class PeopleController : Controller
    {
        private CafeDbContext db = new CafeDbContext();

        // GET: Admin/People
        [HttpPost]
        public ActionResult Index(string searching)
        {

            var links = from l in db.People // lấy toàn bộ liên kết
                        select l;

            if (!String.IsNullOrEmpty(searching)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                links = links.Where(s => s.PersonName.Contains(searching)); //lọc theo chuỗi tìm kiếm
            }

            return View(links); //trả về kết quả
            
        }
       [HttpGet]
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }


        // GET: Admin/People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PERSON pERSON = db.People.Find(id);
            if (pERSON == null)
            {
                return HttpNotFound();
            }
            return View(pERSON);
        }

        // GET: Admin/People/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,Personusername,PersonPassword,PersonEmail,PersonName,PersonPhone,PersonAdress,CreatedDate")] PERSON pERSON)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(pERSON);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pERSON);
        }

        // GET: Admin/People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PERSON pERSON = db.People.Find(id);
            if (pERSON == null)
            {
                return HttpNotFound();
            }
            return View(pERSON);
        }

        // POST: Admin/People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,Personusername,PersonPassword,PersonEmail,PersonName,PersonPhone,PersonAdress,CreatedDate")] PERSON pERSON)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pERSON).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pERSON);
        }

        // GET: Admin/People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PERSON pERSON = db.People.Find(id);
            if (pERSON == null)
            {
                return HttpNotFound();
            }
            return View(pERSON);
        }

        // POST: Admin/People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PERSON pERSON = db.People.Find(id);
            db.People.Remove(pERSON);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CAFE_VIP/Areas/Admin/Controllers/ProductController.cs
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CAFE_VIP.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        CafeDbContext db = new CafeDbContext();
        // GET: Admin/Product
        public ActionResult Index()
        {
            var lstsp = db.PRODUCTs.OrderBy(x => x.ProductID ).ToList();
            return View(lstsp);
        }
        public ActionResult Create()
        {
            return View();
        }
    }
}

CAFE_VIP/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Sản Phẩm
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/paper-dashboard.css" rel="stylesheet" />
    <link href="~/Content/css/admin.css" rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="white" data-active-color="danger">
            <div class="logo">
                <a href="#" class="simple-text logo-mini">
                    <div class="logo-image-small">
                        <img src="/Content/images/logo-small.png">
                    </div>
                </a>
                <a href="#" class="simple-text logo-normal">
                    Coffee Manager
                </a>
            </div>
            <div class="sidebar-wrapper">

                <ul class="nav">
                    <li class="active ">

                        @Html.ActionLink("HOME", "HomeAdmin", "Admin", null, new { @class = "click" })
                    </li>
                    <li>
                        @Html.ActionLink("PRODUCT", "Index", "Product", null, new { @class = "click" })
                    </li>
                    <li >

                        @Html.ActionLink("CATELOGY", "Index", "Catelogy", null, new { @class = "click" })
                    </li>
                    <li>
                        @Html.ActionLink("CUSTOMER", "Index", "CUSTOMERs", null, new { @class = "click" })
                    </li>
                    <li >

                        @Html.ActionLink("PERSON", "Index", "People", null, new { @class = "click" })
                    </li>
                    <li>
                        @Html.ActionLink("ORDER","Index", "Order", null, new { @class = "click" })
                    </li>
                    <li >

                        @Html.ActionLink("RESOURCE", "Index", "RESOURCES", null, new { @class = "click" })
                    </li>
                    
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="index.html">Coffee Hello</a>
                    </div>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a href="admin.html" class="nav-link btn-rotate">
                                    <p>
                                        <span class="d-lg-none d-md-block">Sản Phẩm</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="list.html" class="nav-link btn-rotate">
                                    <p>
                                        <span class="d-lg-none d-md-block">List khách hàng</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="index.html" class="nav-link btn-rotate">
                                    <p>
                                        <span class="d-lg-none d-md-block">Coffee Hello</span>
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            @RenderBody()
        </div>
        <!-- Footer -->
        <footer class="footer footer-black  footer-white ">
            <div class="container-fluid">
                <div class="row">
                    <nav class="footer-nav">
                        <ul>
                            <li>@Html.ActionLink("Coffee Hello", "Index", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </footer>
    </div>
    <!--   Core JS Files   -->
    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
</body>

</html>